#!/usr/bin/env bash
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENVRC_LOCAL="$REPO_ROOT/.envrc.local"
# Written by older versions of this wizard; nothing reads them anymore.
RETIRED_VARS="MACHINE_MODE GATEWAY_BASE_URL ANTHROPIC_API_KEY DATABASE_URL SEARXNG_API_BASE AWS_BEARER_TOKEN_BEDROCK AWS_REGION"

# ── helpers ──────────────────────────────────────────────────────────────────

print_header() { printf '\n\033[1;36m==> %s\033[0m\n' "$1"; }
print_info()   { printf '    \033[0;32m%s\033[0m\n' "$1"; }
print_warn()   { printf '    \033[0;33m%s\033[0m\n' "$1"; }
print_err()    { printf '    \033[0;31m%s\033[0m\n' "$1" >&2; }

ask() {
  local prompt="$1" default="${2:-}"
  local display_default="${default:+ [$default]}"
  printf '  %s%s: ' "$prompt" "$display_default"
  read -r REPLY
  REPLY="${REPLY:-$default}"
}

# Read a variable's value from .envrc.local (strips quotes)
read_envrc_var() {
  local var="$1"
  [[ -f "$ENVRC_LOCAL" ]] || return 0
  grep -E "^export ${var}=" "$ENVRC_LOCAL" | tail -1 | cut -d= -f2- | tr -d "'\"" || true
}

# Set (or, with an empty value, remove) one variable in .envrc.local, leaving
# every other line as the user left it.
set_envrc_var() {
  local var="$1" val="$2" tmp
  tmp="$(mktemp)"
  if [[ -f "$ENVRC_LOCAL" ]]; then
    grep -vE "^export ${var}=" "$ENVRC_LOCAL" > "$tmp" || true
  else
    printf '# Written by scripts/setup.sh. Machine-local secrets; never commit.\n' > "$tmp"
  fi
  if [[ -n "$val" ]]; then printf 'export %s=%s\n' "$var" "$val" >> "$tmp"; fi
  chmod 600 "$tmp"
  mv "$tmp" "$ENVRC_LOCAL"
}

reuse_or_generate() {
  local existing
  existing="$(read_envrc_var "$1")"
  if [[ -n "$existing" ]]; then printf '%s' "$existing"; else printf '%s%s' "$2" "$(openssl rand -hex "$3")"; fi
}

list_ipv4() {
  if command -v ip >/dev/null 2>&1; then
    ip -4 -o addr show | awk '{sub(/\/.*/, "", $4); printf "      %-16s (%s)\n", $4, $2}'
  else
    ifconfig | awk '/^[^ \t]/ {iface = $1; sub(/:$/, "", iface)} /inet / {printf "      %-16s (%s)\n", $2, iface}'
  fi
}

# Render a committed <file>.example template into the git-ignored live <file>,
# prepending a "do not edit" banner. Any extra args are passed to sed as `-e`
# expressions for value substitution (e.g. the max_budget placeholder).
render_config() {
  local example="$1" output="$2"; shift 2
  local sed_args=() expr
  for expr in "$@"; do sed_args+=(-e "$expr"); done
  {
    printf '# ─────────────────────────────────────────────────────────────────────\n'
    printf '# GENERATED by `make setup` from %s — DO NOT EDIT.\n' "$(basename "$example")"
    printf '# Edits here are overwritten on the next `make setup`. Change values in\n'
    printf '# %s (or .envrc.local), then re-run `make setup`.\n' "$example"
    printf '# ─────────────────────────────────────────────────────────────────────\n'
    if [[ ${#sed_args[@]} -gt 0 ]]; then
      sed "${sed_args[@]}" "$REPO_ROOT/$example"
    else
      cat "$REPO_ROOT/$example"
    fi
  } > "$REPO_ROOT/$output"
}

# ── prerequisites ─────────────────────────────────────────────────────────────

print_header "Checking prerequisites"
for tool in devbox openssl; do
  command -v "$tool" >/dev/null 2>&1 || {
    print_err "$tool is not installed."
    [[ "$tool" == devbox ]] && print_err "Install it from https://www.jetify.com/devbox/docs/installing_devbox/"
    exit 1
  }
done
print_info "devbox and openssl found."

# ── collect config values ─────────────────────────────────────────────────────

print_header "Listen address"
printf '  LiteLLM listens on one address. Pick the one your coding-agent VM can reach,\n'
printf '  usually the host side of the VM network. Addresses on this machine:\n'
list_ipv4
EXISTING_HOST="$(read_envrc_var LITELLM_HOST)"
ask "Listen address" "${EXISTING_HOST:-127.0.0.1}"
LITELLM_HOST="$REPLY"
if [[ "$LITELLM_HOST" == "0.0.0.0" ]]; then
  print_warn "0.0.0.0 exposes the gateway on every network this machine joins, guarded only by its keys."
fi

print_header "Gateway configuration"
LITELLM_MASTER_KEY="$(reuse_or_generate LITELLM_MASTER_KEY sk- 16)"
SEARXNG_SECRET="$(reuse_or_generate SEARXNG_SECRET "" 32)"
POSTGRES_PASSWORD="$(reuse_or_generate POSTGRES_PASSWORD "" 24)"
print_info "Master key, SearXNG secret, and Postgres password are ready (existing values are kept)."

EXISTING_MAX_BUDGET="$(read_envrc_var LITELLM_MAX_BUDGET)"
while true; do
  ask "LiteLLM max budget in USD per 30d" "${EXISTING_MAX_BUDGET:-120}"
  if [[ "$REPLY" =~ ^[0-9]+([.][0-9]+)?$ ]]; then break; fi
  print_err "Enter a number, like 120 or 57.5."
done
LITELLM_MAX_BUDGET="$REPLY"

# ── write .envrc.local ────────────────────────────────────────────────────────

print_header "Writing .envrc.local"
for var in $RETIRED_VARS; do
  if [[ -n "$(read_envrc_var "$var")" ]]; then
    set_envrc_var "$var" ""
    print_warn "Removed $var, which is no longer used."
  fi
done
set_envrc_var LITELLM_HOST "$LITELLM_HOST"
set_envrc_var LITELLM_MASTER_KEY "$LITELLM_MASTER_KEY"
set_envrc_var LITELLM_MAX_BUDGET "$LITELLM_MAX_BUDGET"
set_envrc_var SEARXNG_SECRET "$SEARXNG_SECRET"
set_envrc_var POSTGRES_PASSWORD "$POSTGRES_PASSWORD"
print_info "Updated $ENVRC_LOCAL. Lines you added yourself are kept."

# ── render generated service config ───────────────────────────────────────────
# litellm/config.yaml and searxng/settings.yml are git-ignored build artifacts
# rendered from their committed *.example templates.

print_header "Rendering service config"
render_config "litellm/config.yaml.example" "litellm/config.yaml" \
  "s|__LITELLM_MAX_BUDGET__|${LITELLM_MAX_BUDGET}|"
render_config "searxng/settings.yml.example" "searxng/settings.yml"
print_info "Wrote litellm/config.yaml (max_budget=${LITELLM_MAX_BUDGET}) and searxng/settings.yml"

# ── devbox install ────────────────────────────────────────────────────────────

print_header "Installing devbox packages"
(cd "$REPO_ROOT" && devbox install)
eval "$(cd "$REPO_ROOT" && devbox shellenv)"

if command -v direnv >/dev/null 2>&1; then
  (cd "$REPO_ROOT" && direnv allow)
fi

# ── LiteLLM install ──────────────────────────────────────────────────────────

print_header "Installing LiteLLM into .venv"
(
  cd "$REPO_ROOT"
  uv venv .venv --quiet --allow-existing
  uv pip install --python .venv/bin/python --require-hashes -r requirements.txt --quiet
)
print_info "LiteLLM installed at .venv/bin/litellm"

# LiteLLM applies its database migrations on start but expects the Prisma
# client to be generated already.
print_header "Generating Prisma client"
LITELLM_SCHEMA="$(ls "$REPO_ROOT"/.venv/lib/python*/site-packages/litellm/proxy/schema.prisma)"
(cd "$REPO_ROOT" && PATH="$REPO_ROOT/.venv/bin:$PATH" .venv/bin/prisma generate --schema "$LITELLM_SCHEMA" > /dev/null)
print_info "Prisma client generated."

# ── Postgres ─────────────────────────────────────────────────────────────────
# LiteLLM needs a database to mint per-agent keys and track spend.

print_header "Initializing Postgres"
PGDATA_DIR="$REPO_ROOT/data/postgres"
if [[ -f "$PGDATA_DIR/PG_VERSION" ]]; then
  print_info "Reusing existing database in data/postgres"
else
  mkdir -p "$REPO_ROOT/data"
  PWFILE="$(mktemp)"
  printf '%s\n' "$POSTGRES_PASSWORD" > "$PWFILE"
  initdb -D "$PGDATA_DIR" -U litellm -A scram-sha-256 -E UTF8 --no-locale --pwfile="$PWFILE" > /dev/null
  rm -f "$PWFILE"
  # Single-user mode logs every checkpoint to stderr; show it only on failure.
  if ! PG_OUT="$(printf 'CREATE DATABASE litellm;\n' | postgres --single -D "$PGDATA_DIR" postgres 2>&1)"; then
    printf '%s\n' "$PG_OUT" >&2
    print_err "Could not create the litellm database."
    exit 1
  fi
  print_info "Created data/postgres with database 'litellm'"
fi

# ── GitHub Copilot sign-in ───────────────────────────────────────────────────

print_header "GitHub Copilot sign-in"
if [[ -f "$REPO_ROOT/data/github_copilot/access-token" ]]; then
  print_info "Signed in. To use another GitHub account, delete data/github_copilot and run 'make copilot-login'."
elif [[ -t 0 ]]; then
  "$REPO_ROOT/scripts/copilot-login.sh" \
    || print_warn "Sign-in did not finish. Run 'make copilot-login' before 'make start'."
else
  print_warn "Not signed in to GitHub Copilot, and stdin is not a terminal. Run 'make copilot-login' before 'make start'."
fi

# ── done ─────────────────────────────────────────────────────────────────────

print_header "Setup complete"
print_info "Start the backend:     make start   (or 'make serve' to watch it in the foreground)"
print_info "Redo Copilot sign-in:  make copilot-login"
print_info "Mint a key per agent:  make new-key NAME=<agent> [BUDGET=<usd>]"
print_info "Agent base URL:        http://${LITELLM_HOST}:4000"
