#!/usr/bin/env bash
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

# ── helpers ──────────────────────────────────────────────────────────────────

print_header() { printf '\n\033[1;36m==> %s\033[0m\n' "$1"; }
print_info()   { printf '    \033[0;32m%s\033[0m\n' "$1"; }
print_warn()   { printf '    \033[0;33m%s\033[0m\n' "$1"; }
print_err()    { printf '    \033[0;31m%s\033[0m\n' "$1" >&2; }

ask() {
  local prompt="$1" default="${2:-}"
  local display_default="${default:+ [$default]}"
  printf '  %s%s: ' "$prompt" "$display_default"
  read -r REPLY
  REPLY="${REPLY:-$default}"
}

# Show first 6 chars of a secret followed by "..." for verification
mask_value() {
  local val="$1" n=6
  if [[ ${#val} -lt $n ]]; then n=${#val}; fi
  printf '%s...' "${val:0:$n}"
}

# Like ask but hides input, shows a masked hint, and keeps existing value on Enter
ask_secret_with_default() {
  local prompt="$1" existing="$2"
  local hint=""
  if [[ -n "$existing" ]]; then hint=" [$(mask_value "$existing"), Enter to keep]"; fi
  printf '  %s%s: ' "$prompt" "$hint"
  read -rs REPLY
  printf '\n'
  if [[ -z "$REPLY" && -n "$existing" ]]; then REPLY="$existing"; fi
}

# Read a variable's value from .envrc.local (strips quotes)
read_envrc_var() {
  local var="$1"
  [[ -f "$REPO_ROOT/.envrc.local" ]] || return 0
  grep -E "^export ${var}=" "$REPO_ROOT/.envrc.local" | cut -d= -f2- | tr -d "'\"" || true
}

confirm() {
  printf '  %s [y/N]: ' "$1"
  read -r REPLY
  [[ "${REPLY,,}" == "y" || "${REPLY,,}" == "yes" ]]
}

# Render a committed <file>.example template into the git-ignored live <file>,
# prepending a "do not edit" banner. Any extra args are passed to sed as `-e`
# expressions for value substitution (e.g. the max_budget placeholder).
render_config() {
  local example="$1" output="$2"; shift 2
  local sed_args=() expr
  for expr in "$@"; do sed_args+=(-e "$expr"); done
  {
    printf '# ─────────────────────────────────────────────────────────────────────\n'
    printf '# GENERATED by `make setup` from %s — DO NOT EDIT.\n' "$(basename "$example")"
    printf '# Edits here are overwritten on the next `make setup`. Change values in\n'
    printf '# %s (or .envrc.local), then re-run `make setup`.\n' "$example"
    printf '# ─────────────────────────────────────────────────────────────────────\n'
    if [[ ${#sed_args[@]} -gt 0 ]]; then
      sed "${sed_args[@]}" "$REPO_ROOT/$example"
    else
      cat "$REPO_ROOT/$example"
    fi
  } > "$REPO_ROOT/$output"
}

# ── prerequisites ─────────────────────────────────────────────────────────────

print_header "Checking prerequisites"
command -v devbox >/dev/null 2>&1 || {
  print_err "devbox is not installed. Install it from https://www.jetify.com/devbox/docs/installing_devbox/"
  exit 1
}
print_info "devbox found."

# ── collect config values ─────────────────────────────────────────────────────

print_header "Gateway configuration"

EXISTING_KEY="$(read_envrc_var LITELLM_MASTER_KEY)"
if [[ -n "$EXISTING_KEY" ]]; then
  LITELLM_MASTER_KEY="$EXISTING_KEY"
  print_info "Reusing existing master key from .envrc.local"
else
  LITELLM_MASTER_KEY="sk-$(python3 -c 'import secrets; print(secrets.token_hex(16))')"
  print_info "Generated new master key."
fi

# SearXNG (local web-search backend) needs a cryptographic secret_key,
# supplied at runtime via SEARXNG_SECRET so it stays out of the repo.
EXISTING_SEARXNG_SECRET="$(read_envrc_var SEARXNG_SECRET)"
if [[ -n "$EXISTING_SEARXNG_SECRET" ]]; then
  SEARXNG_SECRET="$EXISTING_SEARXNG_SECRET"
  print_info "Reusing existing SearXNG secret from .envrc.local"
else
  SEARXNG_SECRET="$(python3 -c 'import secrets; print(secrets.token_hex(32))')"
  print_info "Generated new SearXNG secret."
fi

# Spend cap rendered into the generated litellm/config.yaml as a literal.
EXISTING_MAX_BUDGET="$(read_envrc_var LITELLM_MAX_BUDGET)"
ask "LiteLLM max budget in USD per 30d" "${EXISTING_MAX_BUDGET:-120}"
LITELLM_MAX_BUDGET="$REPLY"

EXISTING_AWS_BEARER_TOKEN="$(read_envrc_var AWS_BEARER_TOKEN_BEDROCK)"
EXISTING_AWS_REGION="$(read_envrc_var AWS_REGION)"
EXISTING_DATABASE_URL="$(read_envrc_var DATABASE_URL)"

print_header "Upstream provider keys (written to .envrc.local only — never committed)"
printf '  AWS Bedrock (press Enter to skip)\n'
ask_secret_with_default "AWS Bearer Token (optional, Enter to skip)" "$EXISTING_AWS_BEARER_TOKEN"
AWS_BEARER_TOKEN_BEDROCK="$REPLY"
ask "AWS Region" "${EXISTING_AWS_REGION:-us-east-1}"
AWS_REGION="$REPLY"

if [[ -z "$AWS_BEARER_TOKEN_BEDROCK" ]]; then
  print_warn "No provider credentials entered — models won't be callable until you add them to .envrc.local."
fi

printf '\n'
ask_secret_with_default "PostgreSQL database URL (optional, Enter to skip)" "$EXISTING_DATABASE_URL"
# Strip GUI-tool query params (e.g. ?statusColor=...&name=...) — keep only the DSN
DATABASE_URL="${REPLY%%\?*}"

# ── write .envrc.local ────────────────────────────────────────────────────────

print_header "Writing .envrc.local"
ENVRC_LOCAL="$REPO_ROOT/.envrc.local"
SKIP_ENVRC=0

if [[ -f "$ENVRC_LOCAL" ]]; then
  print_warn ".envrc.local already exists."
  confirm "Overwrite it?" || SKIP_ENVRC=1
fi

if [[ "$SKIP_ENVRC" -eq 0 ]]; then
  {
    printf '# Generated by scripts/setup.sh — do not commit this file\n'
    printf 'export LITELLM_MASTER_KEY=%s\n' "$LITELLM_MASTER_KEY"
    printf 'export LITELLM_MAX_BUDGET=%s\n' "$LITELLM_MAX_BUDGET"
    printf 'export SEARXNG_SECRET=%s\n' "$SEARXNG_SECRET"
    # URL the websearch_interception callback uses to reach SearXNG. It reads
    # this env var directly — NOT the api_base in litellm/config.yaml. Must
    # match searxng/settings.yml's bind_address:port.
    printf 'export SEARXNG_API_BASE=%s\n' "${SEARXNG_API_BASE:-http://127.0.0.1:8888}"
    if [[ -n "$AWS_BEARER_TOKEN_BEDROCK" ]]; then
      printf 'export AWS_BEARER_TOKEN_BEDROCK=%s\n' "$AWS_BEARER_TOKEN_BEDROCK"
      printf 'export AWS_REGION=%s\n' "$AWS_REGION"
    fi
    [[ -n "$DATABASE_URL" ]] && printf 'export DATABASE_URL=%s\n' "$DATABASE_URL"
  } > "$ENVRC_LOCAL"
  print_info "Wrote $ENVRC_LOCAL"
fi

# ── render generated service config ───────────────────────────────────────────
# litellm/config.yaml and searxng/settings.yml are git-ignored build artifacts
# rendered from their committed *.example templates.

print_header "Rendering service config"
render_config "litellm/config.yaml.example" "litellm/config.yaml" \
  "s|__LITELLM_MAX_BUDGET__|${LITELLM_MAX_BUDGET}|"
render_config "searxng/settings.yml.example" "searxng/settings.yml"
print_info "Wrote litellm/config.yaml (max_budget=${LITELLM_MAX_BUDGET}) and searxng/settings.yml"

# ── devbox install ────────────────────────────────────────────────────────────

print_header "Installing devbox packages"
(cd "$REPO_ROOT" && devbox install)

eval "$(cd "$REPO_ROOT" && devbox shellenv)"

# ── direnv allow ─────────────────────────────────────────────────────────────

print_header "Enabling direnv"
(cd "$REPO_ROOT" && direnv allow)

# ── LiteLLM install ──────────────────────────────────────────────────────────

print_header "Installing LiteLLM into .venv"
(
  cd "$REPO_ROOT"
  uv venv .venv --quiet
  uv pip install --python .venv/bin/python --require-hashes -r requirements.txt --quiet
)
print_info "LiteLLM installed at .venv/bin/litellm"

if [[ -n "$DATABASE_URL" ]]; then
  print_header "Generating Prisma client"
  LITELLM_SCHEMA="$REPO_ROOT/.venv/lib/python3.12/site-packages/litellm/proxy/schema.prisma"
  (cd "$REPO_ROOT" && PATH="$REPO_ROOT/.venv/bin:$PATH" .venv/bin/prisma generate --schema "$LITELLM_SCHEMA")
  print_info "Prisma client generated."

  print_header "Applying database schema (prisma db push)"
  (cd "$REPO_ROOT" && DATABASE_URL="$DATABASE_URL" PATH="$REPO_ROOT/.venv/bin:$PATH" .venv/bin/prisma db push --schema "$LITELLM_SCHEMA")
  print_info "Database schema applied."
fi

# ── done ─────────────────────────────────────────────────────────────────────

print_header "Setup complete"
print_info "Run 'make serve' to start the LiteLLM gateway."
print_info "Open a new shell in this directory (direnv will load the environment automatically)."
