#!/usr/bin/env bash
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

# ── helpers ──────────────────────────────────────────────────────────────────

print_header() { printf '\n\033[1;36m==> %s\033[0m\n' "$1"; }
print_info()   { printf '    \033[0;32m%s\033[0m\n' "$1"; }
print_warn()   { printf '    \033[0;33m%s\033[0m\n' "$1"; }
print_err()    { printf '    \033[0;31m%s\033[0m\n' "$1" >&2; }

ask() {
  local prompt="$1" default="${2:-}"
  local display_default="${default:+ [$default]}"
  printf '  %s%s: ' "$prompt" "$display_default"
  read -r REPLY
  REPLY="${REPLY:-$default}"
}

ask_secret() {
  local prompt="$1"
  printf '  %s: ' "$prompt"
  read -rs REPLY
  printf '\n'
}

confirm() {
  printf '  %s [y/N]: ' "$1"
  read -r REPLY
  [[ "${REPLY,,}" == "y" || "${REPLY,,}" == "yes" ]]
}

# ── prerequisites ─────────────────────────────────────────────────────────────

print_header "Checking prerequisites"
command -v devbox >/dev/null 2>&1 || {
  print_err "devbox is not installed. Install it from https://www.jetify.com/devbox/docs/installing_devbox/"
  exit 1
}
print_info "devbox found."

# ── mode selection ────────────────────────────────────────────────────────────

print_header "Machine mode"
printf '  Choose the mode for this machine:\n'
printf '    1) full   — runs LiteLLM locally AND the clients (Claude Code, pi.dev)\n'
printf '    2) client — runs only the clients, connecting to a LiteLLM gateway elsewhere\n'
ask "Mode (1/full or 2/client)" "1"

case "${REPLY,,}" in
  1|full)   MACHINE_MODE=full   ;;
  2|client) MACHINE_MODE=client ;;
  *)
    print_err "Invalid choice: $REPLY"
    exit 1
    ;;
esac
print_info "Mode: $MACHINE_MODE"

# ── collect config values ─────────────────────────────────────────────────────

print_header "Gateway configuration"

if [[ "$MACHINE_MODE" == "full" ]]; then
  DEFAULT_URL="http://127.0.0.1:4000"
else
  DEFAULT_URL=""
fi

ask "LiteLLM gateway base URL" "$DEFAULT_URL"
GATEWAY_BASE_URL="$REPLY"
if [[ -z "$GATEWAY_BASE_URL" ]]; then
  print_err "Gateway URL is required."
  exit 1
fi

ask_secret "LiteLLM master key (used to authenticate clients to the gateway)"
LITELLM_MASTER_KEY="$REPLY"
if [[ -z "$LITELLM_MASTER_KEY" ]]; then
  print_err "LiteLLM master key is required."
  exit 1
fi

if [[ "$MACHINE_MODE" == "full" ]]; then
  print_header "Upstream provider keys (written to .envrc.local only — never committed)"
  ask_secret "Anthropic API key"
  ANTHROPIC_API_KEY="$REPLY"
  if [[ -z "$ANTHROPIC_API_KEY" ]]; then
    print_err "Anthropic API key is required in full mode."
    exit 1
  fi
fi

# ── write .envrc.local ────────────────────────────────────────────────────────

print_header "Writing .envrc.local"
ENVRC_LOCAL="$REPO_ROOT/.envrc.local"
SKIP_ENVRC=0

if [[ -f "$ENVRC_LOCAL" ]]; then
  print_warn ".envrc.local already exists."
  confirm "Overwrite it?" || SKIP_ENVRC=1
fi

if [[ "$SKIP_ENVRC" -eq 0 ]]; then
  {
    printf '# Generated by scripts/setup.sh — do not commit this file\n'
    printf 'export MACHINE_MODE=%s\n' "$MACHINE_MODE"
    printf 'export GATEWAY_BASE_URL=%s\n' "$GATEWAY_BASE_URL"
    printf 'export LITELLM_MASTER_KEY=%s\n' "$LITELLM_MASTER_KEY"
    if [[ "$MACHINE_MODE" == "full" ]]; then
      printf 'export ANTHROPIC_API_KEY=%s\n' "$ANTHROPIC_API_KEY"
    fi
  } > "$ENVRC_LOCAL"
  print_info "Wrote $ENVRC_LOCAL"
fi

# ── devbox install ────────────────────────────────────────────────────────────

print_header "Installing devbox packages"
(cd "$REPO_ROOT" && devbox install)

# Source devbox-managed tools (uv, direnv, python) into the current shell
eval "$(cd "$REPO_ROOT" && devbox shellenv)"

# ── direnv allow ─────────────────────────────────────────────────────────────

print_header "Enabling direnv"
(cd "$REPO_ROOT" && direnv allow)

# ── pi.dev models.json ────────────────────────────────────────────────────────

print_header "Configuring pi.dev"
PI_CONFIG_DIR="$HOME/.pi/agent"
PI_MODELS_JSON="$PI_CONFIG_DIR/models.json"
SKIP_PI=0

# pi.dev's anthropic provider appends /messages to baseUrl, so include /v1
PI_BASE_URL="${GATEWAY_BASE_URL%/}/v1"

if [[ -f "$PI_MODELS_JSON" ]]; then
  print_warn "$PI_MODELS_JSON already exists."
  confirm "Overwrite it?" || SKIP_PI=1
fi

if [[ "$SKIP_PI" -eq 0 ]]; then
  mkdir -p "$PI_CONFIG_DIR"
  cat > "$PI_MODELS_JSON" <<EOF
{
  "providers": {
    "anthropic": {
      "baseUrl": "${PI_BASE_URL}",
      "apiKey": "\$LITELLM_MASTER_KEY"
    }
  }
}
EOF
  print_info "Wrote $PI_MODELS_JSON"
fi

# ── LiteLLM install (full mode only) ─────────────────────────────────────────

if [[ "$MACHINE_MODE" == "full" ]]; then
  print_header "Installing LiteLLM into .venv"
  (
    cd "$REPO_ROOT"
    uv venv .venv --quiet
    uv pip install --python .venv/bin/python --require-hashes -r requirements.txt --quiet
  )
  print_info "LiteLLM installed at .venv/bin/litellm"
fi

# ── done ─────────────────────────────────────────────────────────────────────

print_header "Setup complete"
if [[ "$MACHINE_MODE" == "full" ]]; then
  print_info "Run 'make serve' to start the LiteLLM gateway."
else
  print_info "Clients configured to reach gateway at $GATEWAY_BASE_URL."
fi
print_info "Open a new shell in this directory (direnv will load the environment automatically)."
